#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\LoginController::index

login:
  path: /login
  controller: App\Controller\LoginController::redirecting

teacher:
  path: /teacher
  controller: App\Controller\TeacherController::teacher

student:
   path: /student
   controller: App\Controller\StudentController::student

logout:
  path: /logout
  #controller: App\Controller\LoginController::login
create_subject:
  path: /teacher/createsubject
  controller: App\Controller\TeacherController::create_subject


