#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\LoginController::index

login:
  path: /login
  controller: App\Controller\LoginController::redirecting

teacher:
  path: /teacher
  controller: App\Controller\TeacherController::teacher

student:
   path: /student
   controller: App\Controller\StudentController::student

logout:
  path: /logout
  #controller: App\Controller\LoginController::login
create_subject:
  path: /teacher/createsubject
  controller: App\Controller\TeacherController::create_subject

formsubject:
  path: /teacher/formsubject
  controller: App\Controller\TeacherController::formsubject

view_subject:
  path: teacher/view_subject
  controller: App\Controller\TeacherController::view_subject

create_exam:
  path: teacher/create_exam
  controller: App\Controller\TeacherController::create_exam


subject:
  path: teacher/subject/{id}
  controller: App\Controller\TeacherController::subject

formquestion:
  path: teacher/formquestion
  controller: App\Controller\TeacherController::formquestion

create_answer:
  path: teacher/create_answer/{id}
  controller: App\Controller\TeacherController::create_answer